// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3fd0k77bxoUvHJ7mCv9oloG9FNsSmf4E',
    appId: '1:800356554103:web:656bc5e274e25bc54b7d72',
    messagingSenderId: '800356554103',
    projectId: 'myuntar-uts-a2908',
    authDomain: 'myuntar-uts-a2908.firebaseapp.com',
    storageBucket: 'myuntar-uts-a2908.firebasestorage.app',
    measurementId: 'G-V1Z5QKPNH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIWqLfl0tgC9Ng0VWj79RDXAF2G7W2ntE',
    appId: '1:800356554103:android:68edfb22a0cb48f44b7d72',
    messagingSenderId: '800356554103',
    projectId: 'myuntar-uts-a2908',
    storageBucket: 'myuntar-uts-a2908.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsjZ72RTVDNi_4jjSP9X024Y5zPaDrakY',
    appId: '1:800356554103:ios:d9fb3a0f31d5196c4b7d72',
    messagingSenderId: '800356554103',
    projectId: 'myuntar-uts-a2908',
    storageBucket: 'myuntar-uts-a2908.firebasestorage.app',
    iosBundleId: 'com.example.sheets1Ios',
  );
}
